version: '3.7'

services:
  app:
    build:
      context: .
      target: base
    ports:
      - 3000:3000
    volumes:
      - open-source-billing-sync:/open-source-billing:nocopy
    depends_on:
      - mysql
    env_file:
      - ./local.env
    command: bundle exec rails s -b 0.0.0.0

  test:
    build:
      context: .
      target: base
    volumes:
      - ./:/open-source-billing
    depends_on:
      - mysql
    env_file:
      - ./test.env
    command: bundle exec guard --no-interactions

  mysql:
    image:  mysql:5
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password


volumes:
  mysql_data:
  open-source-billing-sync:
    external: true
